ClickTickerSample/Models/CampaignRepository.cs
using ClickTickerSample.Hubs;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace ClickTickerSample.Models
{
    public class CampaignRepository
    {
        readonly string _connString = ConfigurationManager.ConnectionStrings["TestModel"].ConnectionString;

        public IEnumerable<DevTest> GetAllDevTest()
        {
            var campaigns = new List<DevTest>();
            using (var connection = new SqlConnection(_connString))
            {
                connection.Open();
                using (var command = new SqlCommand(@"SELECT [ID], [CampaignName], [Date], [Clicks], [Conversions], [Impressions], [AffiliateName] FROM [dbo].[DevTest]", connection))
                {
                    command.Notification = null;

                    var dependency = new SqlDependency(command);
                    dependency.OnChange += new OnChangeEventHandler(dependency_OnChange);

                    if (connection.State == ConnectionState.Closed)
                    {
                        connection.Open();
                    }
                    var reader = command.ExecuteReader();

                    while (reader.Read())
                    {
                        campaigns.Add(item: new DevTest { ID = (int)reader["ID"], CampaignName = (string)reader["CampaignName"], Date = Convert.ToDateTime(reader["Date"]), Clicks = (int)reader["Clicks"], Conversions = (int)reader["Conversions"], Impressions = (int)reader["Impressions"], AffiliateName = (string)reader["AffiliateName"] });
                    }
                }

            }
            return campaigns;


        }

        private void dependency_OnChange(object sender, SqlNotificationEventArgs e)
        {
            if (e.Type == SqlNotificationType.Change)
            {
                CampaignHub.SendCampaign();
            }
        }
    }
}

ClickTickerSample/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClickTickerSample;
using ClickTickerSample.Models;

namespace ClickTickerSample.Controllers
{
    public class CampaignController : Controller
    {
        private Model1 db = new Model1();

        public ActionResult GetCampaign()
        {
            CampaignRepository _campaignRepository = new CampaignRepository();
            return PartialView("_CampaignList", _campaignRepository.GetAllDevTest());
        }

        // GET: Campaign
        public async Task<ActionResult> Index()
        {
            return View(await db.DevTests.ToListAsync());
        }

        private ActionResult View(List<DevTest> list, IEnumerable<DevTest> enumerable)
        {
            throw new NotImplementedException();
        }

        // GET: Campaign/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DevTest devTest = await db.DevTests.FindAsync(id);
            if (devTest == null)
            {
                return HttpNotFound();
            }
            return View(devTest);
        }

        // GET: Campaign/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Campaign/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,CampaignName,Date,Clicks,Conversions,Impressions,AffiliateName")] DevTest devTest)
        {
            if (ModelState.IsValid)
            {
                db.DevTests.Add(devTest);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(devTest);
        }

        // GET: Campaign/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DevTest devTest = await db.DevTests.FindAsync(id);
            if (devTest == null)
            {
                return HttpNotFound();
            }
            return View(devTest);
        }

        // POST: Campaign/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,CampaignName,Date,Clicks,Conversions,Impressions,AffiliateName")] DevTest devTest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(devTest).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(devTest);
        }

        // GET: Campaign/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DevTest devTest = await db.DevTests.FindAsync(id);
            if (devTest == null)
            {
                return HttpNotFound();
            }
            return View(devTest);
        }

        // POST: Campaign/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            DevTest devTest = await db.DevTests.FindAsync(id);
            db.DevTests.Remove(devTest);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClickTickerSample/Views/Campaign/Create.cshtml
@model ClickTickerSample.DevTest

@{
    ViewBag.Title = "Create Campaign";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>DevTest</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CampaignName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CampaignName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CampaignName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Clicks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Clicks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Clicks, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Conversions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Conversions, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Conversions, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Impressions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Impressions, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Impressions, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AffiliateName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AffiliateName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AffiliateName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ClickTickerSample/Views/Campaign/Delete.cshtml
@model ClickTickerSample.DevTest

@{
    ViewBag.Title = "Delete Campaign";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>DevTest</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CampaignName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CampaignName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Clicks)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Clicks)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Conversions)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Conversions)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Impressions)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Impressions)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AffiliateName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AffiliateName)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

ClickTickerSample/Views/Campaign/Details.cshtml
@model ClickTickerSample.DevTest

@{
    ViewBag.Title = "Campaign Details";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>DevTest</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CampaignName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CampaignName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Clicks)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Clicks)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Conversions)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Conversions)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Impressions)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Impressions)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AffiliateName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AffiliateName)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

ClickTickerSample/Views/Campaign/Edit.cshtml
@model ClickTickerSample.DevTest

@{
    ViewBag.Title = "Edit Campaign";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>DevTest</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.CampaignName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CampaignName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CampaignName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Clicks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Clicks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Clicks, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Conversions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Conversions, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Conversions, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Impressions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Impressions, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Impressions, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AffiliateName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AffiliateName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AffiliateName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ClickTickerSample/Views/Campaign/Index.cshtml
@{
    ViewBag.Title = "List Campaigns";
}


@section Scripts{
    <script src="~/Scripts/jquery.signalR-2.2.1.js"></script>
    <script src="~/signalr/hubs"></script>
    <script type="text/javascript">
    $( document ).ready(function() {

        var notifications = $.connection.CampaignHub;
        $.connection.hub.start().done(function () {
            getAllCampaigns();
        }).fail(function (e) {
            alert(e);
        });

        notifications.client.updateCampaign = function () {
            getAllCampaigns()

        };
    });


    function getAllCampaigns()
    {
        var tbl = $('#campaignTable');
        $.ajax({
            url: '@Url.Action("GetCampaign", "Campaign")',
            contentType: 'application/html ; charset:utf-8',
            type: 'GET',
            dataType: 'html'
        }).success(function (result) {
            tbl.empty().append(result);
        }).error(function () {

        });
    }
    </script>

}

<div class="row">
    <div class="col-md-12">
        <div id="campaignTable"></div>
    </div>
</div>

ClickTickerSample/Views/Shared/_CampaignList.cshtml
@model IEnumerable<ClickTickerSample.DevTest>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<style>
    tr td {
        text-align: center;
    }

    tr th {
        text-align: center;
    }
</style>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CampaignName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clicks)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Conversions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Impressions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AffiliateName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CampaignName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Clicks)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Conversions)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Impressions)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AffiliateName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ClickTickerSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Click Ticker Demo", "List", "Campaign", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top: 20px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Application for ClickTicker - By: Manjyot</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>